### ISSUE TITLE
代码运行问题

### ISSUE THREAD

**Issue by yinglili666** [zwx8981/DBCNN-PyTorch#17]
您好，我想请问一下关于代码运行问题。我如果想在LIVE数据库上训练的话，是应该先利用MATLAB的数据生成函数生成数据类型然后训练SCNN，还是可以直接训练DBCNN呢

**Comment by xiongxiongtiao** [comment]
scnn已经训练好放在github上了，直接训练dbcnn发自我的iPhone------------------ 原始邮件 ------------------发件人: song chunying  <notifications@github.com>发送时间: 2020年9月5日 11:17收件人: zwx8981/DBCNN-PyTorch <DBCNN-PyTorch@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[zwx8981/DBCNN-PyTorch] 代码运行问题 (#17)
您好，我想请问一下关于代码运行问题。我如果想在LIVE数据库上训练的话，是应该先利用MATLAB的数据生成函数生成数据类型然后训练SCNN，还是可以直接训练DBCNN呢

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zwx8981/DBCNN-PyTorch/issues/17",
"url": "https://github.com/zwx8981/DBCNN-PyTorch/issues/17",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by yinglili666** [comment]
> scnn已经训练好放在github上了，直接训练dbcnn发自我的iPhone------------------ 原始邮件 ------------------发件人: song chunying <notifications@github.com>发送时间: 2020年9月5日 11:17收件人: zwx8981/DBCNN-PyTorch <DBCNN-PyTorch@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[zwx8981/DBCNN-PyTorch] 代码运行问题 (#17) 您好，我想请问一下关于代码运行问题。我如果想在LIVE数据库上训练的话，是应该先利用MATLAB的数据生成函数生成数据类型然后训练SCNN，还是可以直接训练DBCNN呢 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#17", "url": "#17", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
好的，谢谢您
