### ISSUE TITLE
Output Range for your model?

### ISSUE THREAD

**Issue by tejaschandramohan** [zwx8981/DBCNN-PyTorch#23]
Hi, I am performing inference for my dataset using your model. What is the output range for your model? Is it [1-10] or [1-100]?

**Comment by tejaschandramohan** [comment]
Yes. But what is the range for dbcnn in general? I am not re-training, I am performing inference. 
For dbcnn, you have CSIQ, TID2013 and LIVE Challenge. These datasets have MOS in different scale. It is not clear from the paper to what the output range for the model is.
Is it [1-10] then?

**Comment by zwx8981** [comment]
csiq：0-1，tid2013: 0-9，live challenge：0-100



发自我的iPhone


------------------ Original ------------------
From: tejaschandramohan ***@***.***&gt;
Date: Thu,Oct 7,2021 10:27 AM
To: zwx8981/DBCNN-PyTorch ***@***.***&gt;
Cc: Onionbao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zwx8981/DBCNN-PyTorch] Output Range for your model? (#23)





 
Yes. But what is the range for dbcnn in general? I am not re-training, I am performing inference.
 For dbcnn, you have CSIQ, TID2013 and LIVE Challenge. These datasets have MOS in different scale. It is not clear from the paper to what the output range for the model is.
 Is it [1-10] then?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zwx8981** [comment]
There is no limit about the range of MOS. You can either train the model on your own dataset or a public dataset like live, csiq, live challenge, etc.



发自我的iPhone


------------------ Original ------------------
From: tejaschandramohan ***@***.***&gt;
Date: Thu,Oct 7,2021 4:06 PM
To: zwx8981/DBCNN-PyTorch ***@***.***&gt;
Cc: Onionbao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zwx8981/DBCNN-PyTorch] Output Range for your model? (#23)





 
For me to train this model, how should my images be annotated?
 Should the MOS be in the range 0-9 or it can be 1-5 as well?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tejaschandramohan** [comment]
In that case, as you mention, do I need the matlab code to generate synthetic distorted images and for the split?

**Comment by zwx8981** [comment]
No, the weights of the scnn branch has been released in the git. You only need to train the dbcnn



发自我的iPhone


------------------ Original ------------------
From: tejaschandramohan ***@***.***&gt;
Date: Thu,Oct 7,2021 4:12 PM
To: zwx8981/DBCNN-PyTorch ***@***.***&gt;
Cc: Onionbao ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [zwx8981/DBCNN-PyTorch] Output Range for your model? (#23)





 
In that case, as you mention, do I need the matlab code to generate synthetic distorted images and for the split?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tejaschandramohan** [comment]
Ok. I find it a bit confusing with the 2 repo - pytorch and matlab. I did not find the file you talked about.
Can you elaborate how should I proceed if I want to retrain the pytorch model for my dataset?
