### ISSUE TITLE
Using simple_demo.py

### ISSUE THREAD

**Issue by kangzhao2** [zwx8981/DBCNN-PyTorch#29]
Hi author:

I want to use simple_demo.py to test jpg quality. I set:

> scnn_root = 'pretrained_scnn/scnn.pkl'

> // ckpt = "your path of the checkpoint file"
> image_name = "4.jpg"
> // checkpoint = torch.load(ckpt)
> // model.load_state_dict(checkpoint)

I comment the code of checkpoint, since it has been set in scnn_root, am I right?

“4.jpg” is my test image, and I get the output: Prediction = -0.0054. I think the prediction should be [0, 1], so whats wrong with my codes?

Kang

**Comment by xiongxiongtiao** [comment]
No, you should first train the model on an IQA database, and set the ckpt to the path of the trained checkpoint.

The range of the output depends on the range of MOS/DMOS of the IQA on which your model is trained.

Without trained on any IQA dataset, the weights of the model is just a meaningless random intilizations.


发送自 Windows 10 版邮件应用

发件人: Kang
发送时间: 2022年1月5日 19:40
收件人: zwx8981/DBCNN-PyTorch
抄送: Subscribed
主题: [zwx8981/DBCNN-PyTorch] Using simple_demo.py (Issue #29)

Hi:
I want to use simple_demo.py to test jpg quality. I set:
scnn_root = 'pretrained_scnn/scnn.pkl'
ckpt = "your path of the checkpoint file"
image_name = "4.jpg"
checkpoint = torch.load(ckpt)
model.load_state_dict(checkpoint)
I comment the code of checkpoint, since it has been set in scnn_root, am I right?
“4.jpg” is my test image, and I get the output: Prediction = -0.0054. I think the prediction should be [0, 1], so whats wrong with my codes?
Kang
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
